version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building project..."
  post_build:
    commands:
      - echo "Deploying to Elastic Beanstalk..."
      - eb init -p python-3.12 GladPharmacyBot --region $AWS_REGION
      - eb deploy

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::891377124166:role/gladbot-code-build-2
  environment_name: GladPharmacyBot-env
  application_name: GladPharmacyBot
  region: $AWS_REGION
