version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"  # Change to your AWS region
    ECR_REPO: "891377124166.dkr.ecr.eu-west-2.amazonaws.com"  # Change this
    ECS_CLUSTER: "gladbot-model"  # Change to your ECS cluster name
    ECS_SERVICE: "gladbot-fastapi"  # Change to your ECS service name
    CONTAINER_NAME: "gladbot-api"  # Change to your ECS container name

phases:

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t api:$CODEBUILD_RESOLVED_SOURCE_VERSION .;
      - docker tag api:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REPO/gladbot_api:latest;
      - docker push $ECR_REPO/gladbot_api:latest;

