version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-2"  # Change to your AWS region
    ECR_REPO: "891377124166.dkr.ecr.eu-west-2.amazonaws.com/gladbot_api_codepipeline_test"  # Change this
    ECS_CLUSTER: "gladbot-model"  # Change to your ECS cluster name
    ECS_SERVICE: "gladbot-fastapi"  # Change to your ECS service name
    CONTAINER_NAME: "gladbot-api"  # Change to your ECS container name

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y jq

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - echo "Checking the source branch..."
      - PR_BASE_REF=$(git log -1 --pretty=%B | grep -o 'base/[^ ]*' || echo "")

  build:
    commands:
      - echo "Building Docker images..."
      - if [[ -n "$PR_BASE_REF" ]]; then
          echo "Building base image...";
          docker build -t base:$CODEBUILD_RESOLVED_SOURCE_VERSION -f base_Dockerfile .;
          docker tag base:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REPO/base:$CODEBUILD_RESOLVED_SOURCE_VERSION;
          docker push $ECR_REPO/base:$CODEBUILD_RESOLVED_SOURCE_VERSION;
        fi
      - echo "Building API image...";
      - docker build -t api:$CODEBUILD_RESOLVED_SOURCE_VERSION -f api_Dockerfile .;
      - docker tag api:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REPO/api:$CODEBUILD_RESOLVED_SOURCE_VERSION;
      - docker push $ECR_REPO/api:$CODEBUILD_RESOLVED_SOURCE_VERSION;

